<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Region;
use App\Models\County;

class RegionSeeder extends Seeder
{
    public function run(): void
    {
        $regions = [
            [
                'name' => 'Central Region', 'code' => 'CR', 'is_active' => true,
                'counties' => [
                    ['name' => 'Central Division',    'code' => 'C001', 'district' => 'Kampala'],
                    ['name' => 'Kawempe Division',    'code' => 'C002', 'district' => 'Kampala'],
                    ['name' => 'Makindye Division',   'code' => 'C003', 'district' => 'Kampala'],
                    ['name' => 'Nakawa Division',     'code' => 'C004', 'district' => 'Kampala'],
                    ['name' => 'Rubaga Division',     'code' => 'C005', 'district' => 'Kampala'],
                    ['name' => 'Busiro North',        'code' => 'C006', 'district' => 'Wakiso'],
                    ['name' => 'Busiro South',        'code' => 'C007', 'district' => 'Wakiso'],
                    ['name' => 'Kyadondo East',       'code' => 'C008', 'district' => 'Wakiso'],
                    ['name' => 'Kyadondo West',       'code' => 'C009', 'district' => 'Wakiso'],
                    ['name' => 'Entebbe Municipality','code' => 'C010', 'district' => 'Wakiso'],
                    ['name' => 'Mukono County',       'code' => 'C011', 'district' => 'Mukono'],
                    ['name' => 'Nakifuma County',     'code' => 'C012', 'district' => 'Mukono'],
                    ['name' => 'Buikwe County',       'code' => 'C013', 'district' => 'Buikwe'],
                    ['name' => 'Buvuma Islands',      'code' => 'C014', 'district' => 'Buvuma'],
                    ['name' => 'Kayunga County',      'code' => 'C015', 'district' => 'Kayunga'],
                    ['name' => 'Ntenjeru County',     'code' => 'C016', 'district' => 'Kayunga'],
                    ['name' => 'Bbaale County',       'code' => 'C017', 'district' => 'Kayunga'],
                    ['name' => 'Luweero County',      'code' => 'C018', 'district' => 'Luweero'],
                    ['name' => 'Katikamu County',     'code' => 'C019', 'district' => 'Luweero'],
                    ['name' => 'Bamunanika County',   'code' => 'C020', 'district' => 'Luweero'],
                    ['name' => 'Nakaseke County',     'code' => 'C021', 'district' => 'Nakaseke'],
                    ['name' => 'Nakasongola County',  'code' => 'C022', 'district' => 'Nakasongola'],
                    ['name' => 'Buruli County',       'code' => 'C023', 'district' => 'Nakasongola'],
                    ['name' => 'Mubende County',      'code' => 'C024', 'district' => 'Mubende'],
                    ['name' => 'Kasanda County',      'code' => 'C025', 'district' => 'Mubende'],
                    ['name' => 'Kiboga County',       'code' => 'C026', 'district' => 'Kiboga'],
                    ['name' => 'Kyankwanzi County',   'code' => 'C027', 'district' => 'Kyankwanzi'],
                    ['name' => 'Mityana County',      'code' => 'C028', 'district' => 'Mityana'],
                    ['name' => 'Busujju County',      'code' => 'C029', 'district' => 'Mityana'],
                    ['name' => 'Mawokota North',      'code' => 'C030', 'district' => 'Mpigi'],
                    ['name' => 'Mawokota South',      'code' => 'C031', 'district' => 'Mpigi'],
                    ['name' => 'Gomba County',        'code' => 'C032', 'district' => 'Gomba'],
                    ['name' => 'Masaka County',       'code' => 'C033', 'district' => 'Masaka'],
                    ['name' => 'Bukoto County',       'code' => 'C034', 'district' => 'Masaka'],
                    ['name' => 'Kalungu County',      'code' => 'C035', 'district' => 'Kalungu'],
                    ['name' => 'Bukomansimbi County', 'code' => 'C036', 'district' => 'Bukomansimbi'],
                    ['name' => 'Lwengo County',       'code' => 'C037', 'district' => 'Lwengo'],
                    ['name' => 'Kyotera County',      'code' => 'C038', 'district' => 'Kyotera'],
                    ['name' => 'Rakai County',        'code' => 'C039', 'district' => 'Rakai'],
                    ['name' => 'Kooki County',        'code' => 'C040', 'district' => 'Rakai'],
                    ['name' => 'Sembabule County',    'code' => 'C041', 'district' => 'Sembabule'],
                    ['name' => 'Mawogola County',     'code' => 'C042', 'district' => 'Sembabule'],
                    ['name' => 'Kalangala County',    'code' => 'C043', 'district' => 'Kalangala'],
                    ['name' => 'Lyantonde County',    'code' => 'C044', 'district' => 'Lyantonde'],
                ],
            ],
            [
                'name' => 'Eastern Region', 'code' => 'ER', 'is_active' => true,
                'counties' => [
                    ['name' => 'Jinja County',           'code' => 'E001', 'district' => 'Jinja'],
                    ['name' => 'Butembe County',         'code' => 'E002', 'district' => 'Jinja'],
                    ['name' => 'Mbale County',           'code' => 'E003', 'district' => 'Mbale'],
                    ['name' => 'Bungokho County',        'code' => 'E004', 'district' => 'Mbale'],
                    ['name' => 'Soroti County',          'code' => 'E005', 'district' => 'Soroti'],
                    ['name' => 'Gweri County',           'code' => 'E006', 'district' => 'Soroti'],
                    ['name' => 'Iganga County',          'code' => 'E007', 'district' => 'Iganga'],
                    ['name' => 'Bugabula County',        'code' => 'E008', 'district' => 'Kamuli'],
                    ['name' => 'Tororo County',          'code' => 'E009', 'district' => 'Tororo'],
                    ['name' => 'West Budama County',     'code' => 'E010', 'district' => 'Tororo'],
                    ['name' => 'Busia County',           'code' => 'E011', 'district' => 'Busia'],
                    ['name' => 'Samia-Bugwe County',     'code' => 'E012', 'district' => 'Busia'],
                    ['name' => 'Kamuli County',          'code' => 'E013', 'district' => 'Kamuli'],
                    ['name' => 'Buzaya County',          'code' => 'E014', 'district' => 'Kamuli'],
                    ['name' => 'Pallisa County',         'code' => 'E015', 'district' => 'Pallisa'],
                    ['name' => 'Butebo County',          'code' => 'E016', 'district' => 'Butebo'],
                    ['name' => 'Kumi County',            'code' => 'E017', 'district' => 'Kumi'],
                    ['name' => 'Ngora County',           'code' => 'E018', 'district' => 'Ngora'],
                    ['name' => 'Bukedea County',         'code' => 'E019', 'district' => 'Bukedea'],
                    ['name' => 'Kapchorwa County',       'code' => 'E020', 'district' => 'Kapchorwa'],
                    ['name' => 'Kween County',           'code' => 'E021', 'district' => 'Kween'],
                    ['name' => 'Sironko County',         'code' => 'E022', 'district' => 'Sironko'],
                    ['name' => 'Bududa County',          'code' => 'E023', 'district' => 'Bududa'],
                    ['name' => 'Manafwa County',         'code' => 'E024', 'district' => 'Manafwa'],
                    ['name' => 'Namisindwa County',      'code' => 'E025', 'district' => 'Namisindwa'],
                    ['name' => 'Bulambuli County',       'code' => 'E026', 'district' => 'Bulambuli'],
                    ['name' => 'Kibuku County',          'code' => 'E027', 'district' => 'Kibuku'],
                    ['name' => 'Budaka County',          'code' => 'E028', 'district' => 'Budaka'],
                    ['name' => 'Namutumba County',       'code' => 'E029', 'district' => 'Namutumba'],
                    ['name' => 'Buyende County',         'code' => 'E030', 'district' => 'Buyende'],
                    ['name' => 'Kidera County',          'code' => 'E031', 'district' => 'Buyende'],
                    ['name' => 'Luuka County',           'code' => 'E032', 'district' => 'Luuka'],
                    ['name' => 'Kaliro County',          'code' => 'E033', 'district' => 'Kaliro'],
                    ['name' => 'Mayuge County',          'code' => 'E034', 'district' => 'Mayuge'],
                    ['name' => 'Bugiri County',          'code' => 'E035', 'district' => 'Bugiri'],
                    ['name' => 'Namayingo County',       'code' => 'E036', 'district' => 'Namayingo'],
                    ['name' => 'Serere County',          'code' => 'E037', 'district' => 'Serere'],
                    ['name' => 'Katakwi County',         'code' => 'E038', 'district' => 'Katakwi'],
                    ['name' => 'Amuria County',          'code' => 'E039', 'district' => 'Amuria'],
                    ['name' => 'Kapelebyong County',     'code' => 'E040', 'district' => 'Kapelebyong'],
                    ['name' => 'Kalaki County',          'code' => 'E041', 'district' => 'Kalaki'],
                    ['name' => 'Butebo North',           'code' => 'E042', 'district' => 'Butebo'],
                    ['name' => 'Tororo North',           'code' => 'E043', 'district' => 'Tororo'],
                    ['name' => 'Kibale County (East)',   'code' => 'E044', 'district' => 'Kamuli'],
                    ['name' => 'Namayingo South',        'code' => 'E045', 'district' => 'Namayingo'],
                ],
            ],
            [
                'name' => 'Northern Region', 'code' => 'NR', 'is_active' => true,
                'counties' => [
                    ['name' => 'Gulu County',         'code' => 'N001', 'district' => 'Gulu'],
                    ['name' => 'Aswa County',         'code' => 'N002', 'district' => 'Gulu'],
                    ['name' => 'Omoro County',        'code' => 'N003', 'district' => 'Omoro'],
                    ['name' => 'Lira County',         'code' => 'N004', 'district' => 'Lira'],
                    ['name' => 'Erute County',        'code' => 'N005', 'district' => 'Lira'],
                    ['name' => 'Kole County',         'code' => 'N006', 'district' => 'Kole'],
                    ['name' => 'Alebtong County',     'code' => 'N007', 'district' => 'Alebtong'],
                    ['name' => 'Otuke County',        'code' => 'N008', 'district' => 'Otuke'],
                    ['name' => 'Oyam County',         'code' => 'N009', 'district' => 'Oyam'],
                    ['name' => 'Oyam North',          'code' => 'N010', 'district' => 'Oyam'],
                    ['name' => 'Apac County',         'code' => 'N011', 'district' => 'Apac'],
                    ['name' => 'Kwania County',       'code' => 'N012', 'district' => 'Kwania'],
                    ['name' => 'Dokolo County',       'code' => 'N013', 'district' => 'Dokolo'],
                    ['name' => 'Amolatar County',     'code' => 'N014', 'district' => 'Amolatar'],
                    ['name' => 'Kitgum County',       'code' => 'N015', 'district' => 'Kitgum'],
                    ['name' => 'Chua County',         'code' => 'N016', 'district' => 'Kitgum'],
                    ['name' => 'Lamwo County',        'code' => 'N017', 'district' => 'Lamwo'],
                    ['name' => 'Pader County',        'code' => 'N018', 'district' => 'Pader'],
                    ['name' => 'Agago County',        'code' => 'N019', 'district' => 'Agago'],
                    ['name' => 'Agago North',         'code' => 'N020', 'district' => 'Agago'],
                    ['name' => 'Amuru County',        'code' => 'N021', 'district' => 'Amuru'],
                    ['name' => 'Nwoya County',        'code' => 'N022', 'district' => 'Nwoya'],
                    ['name' => 'Arua County',         'code' => 'N023', 'district' => 'Arua'],
                    ['name' => 'Vurra County',        'code' => 'N024', 'district' => 'Arua'],
                    ['name' => 'Terego County',       'code' => 'N025', 'district' => 'Terego'],
                    ['name' => 'Madi-Okollo County',  'code' => 'N026', 'district' => 'Madi-Okollo'],
                    ['name' => 'Maracha County',      'code' => 'N027', 'district' => 'Maracha'],
                    ['name' => 'Koboko County',       'code' => 'N028', 'district' => 'Koboko'],
                    ['name' => 'Yumbe County',        'code' => 'N029', 'district' => 'Yumbe'],
                    ['name' => 'Zombo County',        'code' => 'N030', 'district' => 'Zombo'],
                    ['name' => 'Nebbi County',        'code' => 'N031', 'district' => 'Nebbi'],
                    ['name' => 'Jonam County',        'code' => 'N032', 'district' => 'Nebbi'],
                    ['name' => 'Pakwach County',      'code' => 'N033', 'district' => 'Pakwach'],
                    ['name' => 'Adjumani County',     'code' => 'N034', 'district' => 'Adjumani'],
                    ['name' => 'Moyo County',         'code' => 'N035', 'district' => 'Moyo'],
                    ['name' => 'Obongi County',       'code' => 'N036', 'district' => 'Obongi'],
                    ['name' => 'Moroto County',       'code' => 'N037', 'district' => 'Moroto'],
                    ['name' => 'Rupe County',         'code' => 'N038', 'district' => 'Moroto'],
                    ['name' => 'Napak County',        'code' => 'N039', 'district' => 'Napak'],
                    ['name' => 'Nakapiripirit County','code' => 'N040', 'district' => 'Nakapiripirit'],
                    ['name' => 'Amudat County',       'code' => 'N041', 'district' => 'Amudat'],
                    ['name' => 'Kotido County',       'code' => 'N042', 'district' => 'Kotido'],
                    ['name' => 'Jie County',          'code' => 'N043', 'district' => 'Kotido'],
                    ['name' => 'Abim County',         'code' => 'N044', 'district' => 'Abim'],
                    ['name' => 'Kaabong County',      'code' => 'N045', 'district' => 'Kaabong'],
                    ['name' => 'Karenga County',      'code' => 'N046', 'district' => 'Karenga'],
                    ['name' => 'Nabilatuk County',    'code' => 'N047', 'district' => 'Nabilatuk'],
                    ['name' => 'Buliisa County',      'code' => 'N048', 'district' => 'Buliisa'],
                    ['name' => 'Masindi County',      'code' => 'N049', 'district' => 'Masindi'],
                    ['name' => 'Bujenje County',      'code' => 'N050', 'district' => 'Masindi'],
                    ['name' => 'Kiryandongo County',  'code' => 'N051', 'district' => 'Kiryandongo'],
                    ['name' => 'Kibanda County',      'code' => 'N052', 'district' => 'Kiryandongo'],
                    ['name' => 'Gulu East',           'code' => 'N053', 'district' => 'Gulu'],
                ],
            ],
            [
                'name' => 'Western Region', 'code' => 'WR', 'is_active' => true,
                'counties' => [
                    ['name' => 'Kashari County',         'code' => 'W001', 'district' => 'Mbarara'],
                    ['name' => 'Kashaari County',        'code' => 'W002', 'district' => 'Mbarara'],
                    ['name' => 'Rwampara County',        'code' => 'W003', 'district' => 'Rwampara'],
                    ['name' => 'Isingiro County',        'code' => 'W004', 'district' => 'Isingiro'],
                    ['name' => 'Isingiro North',         'code' => 'W005', 'district' => 'Isingiro'],
                    ['name' => 'Kiruhura County',        'code' => 'W006', 'district' => 'Kiruhura'],
                    ['name' => 'Ibanda County',          'code' => 'W007', 'district' => 'Ibanda'],
                    ['name' => 'Ibanda North',           'code' => 'W008', 'district' => 'Ibanda'],
                    ['name' => 'Sheema County',          'code' => 'W009', 'district' => 'Sheema'],
                    ['name' => 'Sheema North',           'code' => 'W010', 'district' => 'Sheema'],
                    ['name' => 'Bushenyi County',        'code' => 'W011', 'district' => 'Bushenyi'],
                    ['name' => 'Igara County East',      'code' => 'W012', 'district' => 'Bushenyi'],
                    ['name' => 'Igara County West',      'code' => 'W013', 'district' => 'Bushenyi'],
                    ['name' => 'Mitooma County',         'code' => 'W014', 'district' => 'Mitooma'],
                    ['name' => 'Buhweju County',         'code' => 'W015', 'district' => 'Buhweju'],
                    ['name' => 'Rubirizi County',        'code' => 'W016', 'district' => 'Rubirizi'],
                    ['name' => 'Bunyaruguru County',     'code' => 'W017', 'district' => 'Rubirizi'],
                    ['name' => 'Ntungamo County',        'code' => 'W018', 'district' => 'Ntungamo'],
                    ['name' => 'Rushenyi County',        'code' => 'W019', 'district' => 'Ntungamo'],
                    ['name' => 'Kabale County',          'code' => 'W020', 'district' => 'Kabale'],
                    ['name' => 'Ndorwa County East',     'code' => 'W021', 'district' => 'Kabale'],
                    ['name' => 'Ndorwa County West',     'code' => 'W022', 'district' => 'Kabale'],
                    ['name' => 'Rubanda County',         'code' => 'W023', 'district' => 'Rubanda'],
                    ['name' => 'Kisoro County',          'code' => 'W024', 'district' => 'Kisoro'],
                    ['name' => 'Bukimbiri County',       'code' => 'W025', 'district' => 'Kisoro'],
                    ['name' => 'Rukungiri County',       'code' => 'W026', 'district' => 'Rukungiri'],
                    ['name' => 'Rubabo County',          'code' => 'W027', 'district' => 'Rukungiri'],
                    ['name' => 'Kanungu County',         'code' => 'W028', 'district' => 'Kanungu'],
                    ['name' => 'Kinkizi County East',    'code' => 'W029', 'district' => 'Kanungu'],
                    ['name' => 'Kinkizi County West',    'code' => 'W030', 'district' => 'Kanungu'],
                    ['name' => 'Kasese County',          'code' => 'W031', 'district' => 'Kasese'],
                    ['name' => 'Bukonzo County East',    'code' => 'W032', 'district' => 'Kasese'],
                    ['name' => 'Bukonzo County West',    'code' => 'W033', 'district' => 'Kasese'],
                    ['name' => 'Busongora County North', 'code' => 'W034', 'district' => 'Kasese'],
                    ['name' => 'Busongora County South', 'code' => 'W035', 'district' => 'Kasese'],
                    ['name' => 'Burahya County',         'code' => 'W036', 'district' => 'Kabarole'],
                    ['name' => 'Kabarole County',        'code' => 'W037', 'district' => 'Kabarole'],
                    ['name' => 'Bundibugyo County',      'code' => 'W038', 'district' => 'Bundibugyo'],
                    ['name' => 'Bwamba County',          'code' => 'W039', 'district' => 'Bundibugyo'],
                    ['name' => 'Ntoroko County',         'code' => 'W040', 'district' => 'Ntoroko'],
                    ['name' => 'Kyenjojo County',        'code' => 'W041', 'district' => 'Kyenjojo'],
                    ['name' => 'Mwenge County North',    'code' => 'W042', 'district' => 'Kyenjojo'],
                    ['name' => 'Mwenge County South',    'code' => 'W043', 'district' => 'Kyenjojo'],
                    ['name' => 'Kyegegwa County',        'code' => 'W044', 'district' => 'Kyegegwa'],
                    ['name' => 'Kamwenge County',        'code' => 'W045', 'district' => 'Kamwenge'],
                    ['name' => 'Kibale County',          'code' => 'W046', 'district' => 'Kibale'],
                    ['name' => 'Kakumiro County',        'code' => 'W047', 'district' => 'Kakumiro'],
                    ['name' => 'Kagadi County',          'code' => 'W048', 'district' => 'Kagadi'],
                    ['name' => 'Kibaale County',         'code' => 'W049', 'district' => 'Kibaale'],
                    ['name' => 'Hoima County',           'code' => 'W050', 'district' => 'Hoima'],
                    ['name' => 'Buhaguzi County',        'code' => 'W051', 'district' => 'Hoima'],
                    ['name' => 'Kaiso-Tonya County',     'code' => 'W052', 'district' => 'Hoima'],
                    ['name' => 'Lyantonde County (W)',   'code' => 'W053', 'district' => 'Lyantonde'],
                    ['name' => 'Sembabule West',         'code' => 'W054', 'district' => 'Sembabule'],
                    ['name' => 'Mwenge County West',     'code' => 'W055', 'district' => 'Kyenjojo'],
                    ['name' => 'Kamwenge North',         'code' => 'W056', 'district' => 'Kamwenge'],
                    ['name' => 'Bundibugyo East',        'code' => 'W057', 'district' => 'Bundibugyo'],
                    ['name' => 'Kiruhura East',          'code' => 'W058', 'district' => 'Kiruhura'],
                    ['name' => 'Fort Portal City',       'code' => 'W059', 'district' => 'Kabarole'],
                ],
            ],
        ];

        $totalCounties = 0;

        foreach ($regions as $regionData) {
            $counties = $regionData['counties'];
            unset($regionData['counties']);

            $region = Region::updateOrCreate(['code' => $regionData['code']], $regionData);

            foreach ($counties as $countyData) {
                County::updateOrCreate(
                    ['code' => $countyData['code']],
                    array_merge($countyData, ['region_id' => $region->id, 'is_active' => true])
                );
                $totalCounties++;
            }
        }

        $this->command->info("Regions and counties seeded: 4 regions, {$totalCounties} counties.");
    }
}
